# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  FL_ANKLE_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  FL_ANKLE_R:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  FL_ANKLE_Y:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  FL_HIP_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  FL_HIP_R:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  FL_HIP_Y:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  FL_KNEE_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  FR_ANKLE_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  FR_ANKLE_R:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  FR_ANKLE_Y:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  FR_HIP_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  FR_HIP_R:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  FR_HIP_Y:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  FR_KNEE_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  RL_ANKLE_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  RL_ANKLE_R:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  RL_ANKLE_Y:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RL_HIP_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  RL_HIP_R:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  RL_HIP_Y:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RL_KNEE_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  RR_ANKLE_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  RR_ANKLE_R:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  RR_ANKLE_Y:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RR_HIP_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  RR_HIP_R:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0
  RR_HIP_Y:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RR_KNEE_P:
    has_velocity_limits: true
    max_velocity: 1000000
    has_acceleration_limits: false
    max_acceleration: 0